# Python
- Introduction
- Welcome to python

Welcome to **data analysis workshop** 
Welcome to **geethanjali institute of science and technology**


<img src="image.jpg">






[google](https://github.com/)

# Numpy
- Numpy means numerical python
- It works as data manipulating mathematical operations and statistical analysis


In [2]:
## creating numpy array
import numpy as np
a=np.array([1,2,3,4,5])# single dimensional array

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a.size

5

In [6]:
a.shape

(5,)

In [7]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
a2.ndim

2

In [9]:
a2.shape

(2, 5)

In [10]:
a3=np.array([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7]])
a3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [11]:
np.random.random()

0.9232828187939621

In [12]:
a3.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [13]:
a3.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [14]:
a3.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [15]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a2=np.arange(1,100)

In [17]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
a2[a2%7==5]

array([ 5, 12, 19, 26, 33, 40, 47, 54, 61, 68, 75, 82, 89, 96])

In [19]:
a3.size

15

In [20]:
a3.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [21]:
a3=np.arange(1,31)

In [22]:
a3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
a3.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [24]:
a4=a3.reshape(3,10)

In [25]:
a4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [26]:
a4[0::2,4:7:2]

array([[ 5,  7],
       [25, 27]])

In [27]:
a4[0::2,1::2]

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [28]:
a4[2::2]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [29]:
a4[0::2,0::4]

array([[ 1,  5,  9],
       [21, 25, 29]])

In [30]:
a4

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [31]:
a1=np.ones([3,5])

In [32]:
a1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
a3=np.zeros([3,5])

In [34]:
a3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.vstack([a1,a3])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [38]:
np.linspace(1,20,100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

In [39]:
np.full(15,10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [40]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [41]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [42]:
a3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.hsplit(a3,5)

[array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.]]),
 array([[0.],
        [0.],
        [0.]])]

In [48]:
a4=np.arange(1,31)

In [49]:
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
a4.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [51]:
a5=a4.reshape(6,5)

In [52]:
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [53]:
a5.sum()

465

In [54]:
a5.min()

1

In [55]:
a5.std()

8.65544144839919

In [56]:
a5.max()

30

In [60]:
a5.diagonal()

array([ 1,  7, 13, 19, 25])

In [62]:
np.vsplit(a3,3)

[array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.]])]

In [63]:
a5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
a5.T

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [65]:
np.exp(np.arange(1,10))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [69]:
np.median(a5)

15.5

In [73]:
np.percentile(a5,24)

7.96

In [74]:
np.sin(a5)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175],
       [ 0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162]])

In [75]:
np.tan(a3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
np.cos(a2)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145,
        0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
       -0.12796369,  0.76541405,  0.95507364,  0.26664293, -0.66693806,
       -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,  0.52532199,
       -0.43217794, -0.99233547, -0.64014434,  0.30059254,  0.96496603,
        0.7421542 , -0.16299078, -0.91828279, -0.82930983,  0.02212676,
        0.85322011,  0.89986683,  0.11918014, -0.77108022, -0.95241298,
       -0.25810164,  0.67350716,  0.98589658,  0.39185723, -0.56245385,
       -0.99964746, -0.5177698 ,  0.44014302,  0.99339038,  0.63

In [77]:
np.sinh(a5)

array([[1.17520119e+00, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
        7.42032106e+01],
       [2.01713157e+02, 5.48316123e+02, 1.49047883e+03, 4.05154190e+03,
        1.10132329e+04],
       [2.99370708e+04, 8.13773957e+04, 2.21206696e+05, 6.01302142e+05,
        1.63450869e+06],
       [4.44305526e+06, 1.20774764e+07, 3.28299846e+07, 8.92411505e+07,
        2.42582598e+08],
       [6.59407867e+08, 1.79245642e+09, 4.87240172e+09, 1.32445611e+10,
        3.60024497e+10],
       [9.78648047e+10, 2.66024120e+11, 7.23128532e+11, 1.96566715e+12,
        5.34323729e+12]])

In [78]:
np.cosh(a)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284, 74.20994852])